companieshouse/lfp-appeals-api

README.md, pom.xml, src/main/java/uk/gov/companieshouse/AppealApplication.java, src/main/resources/application.yml
Changes include:
* New dependancy spring-boot-starter-data-mongodb in pom
* 'repository' package to hold interfaces extending Spring MongoRepository
* Annotation '@EnableMongoRepositories' on the main class to scan the package and look for any MongoRepository interfaces
* Database uri in yml file
=> Started adding mongodb configuration

src/main/java/uk/gov/companieshouse/mapper/AttachmentMapper.java, src/main/java/uk/gov/companieshouse/model/Attachment.java, src/main/java/uk/gov/companieshouse/service/AppealService.java, src/test/java/uk/gov/companieshouse/TestData.java, src/test/java/uk/gov/companieshouse/mapper/AppealMapperTest.java, src/test/java/uk/gov/companieshouse/mapper/AttachmentMapperTest.java, src/test/java/uk/gov/companieshouse/service/AppealServiceTest.java
JIRA: https://companieshouse.atlassian.net/browse/LFA-1595
=> feat: send attachment list to chips

README.md
At time of PR creation, this PR relies on changes to docker env, checkout `appeals/feat/enable_swagger`
=> chore: update readme with docker env instructions + swagger

pom.xml
Add CH structured logging library in Appeals API
Resolves [BI-8242](https://companieshouse.atlassian.net/browse/BI-8242)
=> Add CH structured logging library in Appeals API

src/main/java/uk/gov/companieshouse/service/AppealService.java, src/test/java/uk/gov/companieshouse/service/AppealServiceTest.java
Hotfix for https://companieshouse.atlassian.net/browse/BI-8264
=> Sonar Fixes and hotfix removal of test code

specs/lfp-appeals-api-spec.json
Updated spec to match Web service objects
=> Updated Spec to include other person

src/main/java/uk/gov/companieshouse/database/entity/IllnessReasonEntity.java
Resolves: https://companieshouse.atlassian.net/browse/BI-8283
=> Added Illness Reason Entity Model

src/main/java/uk/gov/companieshouse/service/AppealService.java, src/test/java/uk/gov/companieshouse/service/AppealServiceTest.java
=> Formatting fix for contact builder

src/main/java/uk/gov/companieshouse/service/AppealService.java, src/main/java/uk/gov/companieshouse/util/ChipsContactDescriptionFormatter.java, src/test/java/uk/gov/companieshouse/TestUtil.java, src/test/java/uk/gov/companieshouse/mapper/AttachmentMapperTest.java, src/test/java/uk/gov/companieshouse/mapper/IllnessReasonMapperTest.java, src/test/java/uk/gov/companieshouse/mapper/OtherReasonMapperTest.java, src/test/java/uk/gov/companieshouse/model/validator/AppealReasonValidatorTest.java, src/test/java/uk/gov/companieshouse/service/AppealServiceTest.java, src/test/java/uk/gov/companieshouse/util/ChipsContactDescriptionFormatterTest.java
Resolves [BI-8658](https://companieshouse.atlassian.net/browse/BI-8658)
=> Refactor contact description to use a simple utility class

specs/lfp-appeals-api-spec.json
Updated Spec to add new yourName to createdBy object to match new screens.
Resolves: https://companieshouse.atlassian.net/browse/BI-8543
=> Updated spec to add yourName to createdBy object

specs/lfp-appeals-api-spec.json, src/main/java/uk/gov/companieshouse/database/entity/CreatedByEntity.java, src/main/java/uk/gov/companieshouse/mapper/CreatedByMapper.java, src/main/java/uk/gov/companieshouse/model/Appeal.java, src/main/java/uk/gov/companieshouse/model/CreatedBy.java, src/main/java/uk/gov/companieshouse/util/ChipsContactDescriptionFormatter.java, src/test/java/uk/gov/companieshouse/TestData.java, src/test/java/uk/gov/companieshouse/TestUtil.java, src/test/java/uk/gov/companieshouse/controller/AppealControllerTest_GET.java, src/test/java/uk/gov/companieshouse/mapper/CreatedByMapperTest.java, src/test/java/uk/gov/companieshouse/service/AppealServiceTest.java, src/test/java/uk/gov/companieshouse/util/ChipsContactDescriptionFormatterTest.java, src/test/resources/data/invalidAppealReason.json, src/test/resources/data/validAppeal.json
Also made CreatedBy fields required on spec and with validation
Resolves: https://companieshouse.atlassian.net/browse/BI-8638
=> Added YourName to model + test updates

src/main/java/uk/gov/companieshouse/model/Appeal.java, src/main/java/uk/gov/companieshouse/model/CreatedBy.java
Remove validation for createdBy field to made it optional
Related to [BI-8638](https://companieshouse.atlassian.net/browse/BI-8638)
=> Remove validation for createdBy field to made it optional

src/main/java/uk/gov/companieshouse/mapper/ReasonMapper.java, src/main/java/uk/gov/companieshouse/model/Reason.java, src/main/java/uk/gov/companieshouse/model/validator/AppealReasonValidator.java, src/main/java/uk/gov/companieshouse/util/ChipsContactDescriptionFormatter.java, src/test/java/uk/gov/companieshouse/mapper/ReasonMapperTest.java, src/test/java/uk/gov/companieshouse/model/validator/AppealReasonValidatorTest.java, src/test/java/uk/gov/companieshouse/util/ChipsContactDescriptionFormatterTest.java, src/test/resources/data/invalidAppealReason.json
Rename illness reason object, Fix bug for [BI-8535](https://companieshouse.atlassian.net/browse/BI-8535) story
=> Rename illness reason object

src/main/java/uk/gov/companieshouse/AppealApplication.java, src/main/java/uk/gov/companieshouse/client/ChipsRestClient.java, src/main/java/uk/gov/companieshouse/controller/AppealController.java, src/main/java/uk/gov/companieshouse/model/validator/CompanyNumberValidator.java, src/main/java/uk/gov/companieshouse/service/AppealService.java, src/test/java/uk/gov/companieshouse/TestUtil.java, src/test/java/uk/gov/companieshouse/service/AppealServiceTest.java
Resolves:  https://companieshouse.atlassian.net/browse/BI-8485
Implemented corrected logging for API and Service layer for use on Kibana
Unit tests have been added.
=> Implemented structured logging for API and service

src/main/java/uk/gov/companieshouse/controller/AppealController.java, src/main/java/uk/gov/companieshouse/model/CreatedBy.java, src/main/java/uk/gov/companieshouse/model/validator/RelationshipValidator.java, src/test/java/uk/gov/companieshouse/TestData.java, src/test/java/uk/gov/companieshouse/TestUtil.java, src/test/java/uk/gov/companieshouse/controller/AppealControllerTest_GET.java, src/test/java/uk/gov/companieshouse/controller/AppealControllerTest_POST.java, src/test/java/uk/gov/companieshouse/model/validator/RelationshipValidatorTest.java, src/test/resources/data/invalidRelationshipAppeal.json
Resolves: https://companieshouse.atlassian.net/browse/BI-8747
Added Relationship to Company onto the CreatedBy Object inside the API and added logic + validation for use. 
Added Unit tests
=> Adding relationship to company onto API + tests

src/main/java/uk/gov/companieshouse/service/AppealService.java, src/test/java/uk/gov/companieshouse/service/AppealServiceTest.java
Hotfix for https://companieshouse.atlassian.net/browse/BI-8485
Adding info to logging messages in service layer.
=> Fixed logging message for service

src/main/java/uk/gov/companieshouse/util/ChipsContactDescriptionFormatter.java, src/test/java/uk/gov/companieshouse/util/ChipsContactDescriptionFormatterTest.java
Resolves: https://companieshouse.atlassian.net/browse/BI-8990
Adding "Relationship to Company" to contact description clob for chips
* [x} New feature
=> Added relationship to contact description clob

specs/lfp-appeals-api-spec.json
[BI-9031](https://companieshouse.atlassian.net/browse/BI-9031)
Decision was made in August by Kevin Bradwick to rename yourName to name. Code was updated but the spec wasn't so it's being updated now as the testers use the spec for their test data.
=> Update yourName references to name

specs/lfp-appeals-api-spec.json, src/main/java/uk/gov/companieshouse/controller/AppealController.java, src/main/java/uk/gov/companieshouse/model/validator/EndDateValidator.java, src/main/java/uk/gov/companieshouse/service/AppealService.java, src/main/java/uk/gov/companieshouse/util/ChipsContactDescriptionFormatter.java, src/test/java/uk/gov/companieshouse/TestUtil.java, src/test/java/uk/gov/companieshouse/controller/AppealControllerTest_POST.java, src/test/java/uk/gov/companieshouse/model/validator/EndDateValidatorTest.java, src/test/java/uk/gov/companieshouse/util/ChipsContactDescriptionFormatterTest.java, src/test/resources/data/invalidIllnessEndDate.json
Resolves: https://companieshouse.atlassian.net/browse/BI-8961
Adding Validation against the End Date on the Illness Reason Journey to match changes on the Frontend as to throw a 422 error if End Date is errorenus. 
Added Unit tests to cover new class and updated controller unit tests to catch new 422 error
Added Validation errors to structured logging
Altered Chips Contact Creation to not show Illness End Date if Continued Illness is true + Unit tests
=> BI-8961: Add Validation for Illness End Date

src/main/java/uk/gov/companieshouse/controller/AppealController.java
[BI-8304](https://companieshouse.atlassian.net/browse/BI-8304)
Update usage of company-id in controller endpoints to company-number as per the spec.
=> Update controller endpoints to match spec

src/main/java/uk/gov/companieshouse/service/AppealService.java, src/test/java/uk/gov/companieshouse/client/ChipsRestClientTest.java, src/test/java/uk/gov/companieshouse/controller/AppealControllerPostTest.java
=> Address sonar issues in lfp-appeal-api

pom.xml
Reverts companieshouse/lfp-appeals-api#199
=> Revert "chore: bump json from 20220924 to 20230227"

Makefile, src/main/java/uk/gov/companieshouse/config/ApplicationConfig.java, src/main/java/uk/gov/companieshouse/controller/AppealController.java, src/main/java/uk/gov/companieshouse/email/EmailSendMessageProducer.java, src/main/java/uk/gov/companieshouse/mapper/IllnessReasonMapper.java, src/main/java/uk/gov/companieshouse/mapper/OtherReasonMapper.java, src/main/java/uk/gov/companieshouse/mapper/ReasonMapper.java, src/main/java/uk/gov/companieshouse/service/AppealService.java, src/main/java/uk/gov/companieshouse/service/EmailService.java
* [ X] I have added/updated functional tests where appropriate
=> update to Makefile use constructor injection instead of autowiring

pom.xml
Updating the Shared Services image
=> Updating the Shared Services image

pom.xml
=> update to correct pipeline error in vulnerability check

README.md, pom.xml, terraform/groups/ecs-service/locals.tf
- Update Spring boot to latest version
- Implement the new vulnerability suppression method
- Make sure the Jib plugin docker images are correct
=> Vulnerability update

pom.xml
[ASM-555](https://companieshouse.atlassian.net/browse/ASM-555)
Update CH artifactory url in pom.xml
* [*] Bug fix
[ASM-555]: https://companieshouse.atlassian.net/browse/ASM-555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Updated CH artifactory in pom.xml
